name: Build & Release

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'

      # 4. Clean project
      - name: Clean project
        run: flutter clean

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Get version from pubspec.yaml
      - name: Get version
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //g' | cut -d '+' -f 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 7. Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # 8. Upload to GitHub Releases
      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}